---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: localhost:5001/gateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: gateway-env
        - secretRef:
            name: gateway-secrets
      terminationGracePeriodSeconds: 180