resources:
- deployment.yml
- service.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: gateway-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - services__weather-api__0=http://weather-api:8080
    - services__weather-api__1=https://weather-api:8443
    - ASPNETCORE_URLS=http://+:8080

secretGenerator:
- name: gateway-secrets
  envs:
  - .gateway.secrets
