version: "3.8"
services:
  redis:
    container_name: "redis"
    image: "bitnami/redis:latest"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
    - target: 6379
      published: 6379
    restart: unless-stopped
  weather-api:
    container_name: "weather-api"
    image: "localhost:5001/weather-api:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ConnectionStrings__cache: "redis"
    ports:
    - target: 8080
      published: 10000
    - target: 8443
      published: 10001
    restart: unless-stopped
  gateway:
    container_name: "gateway"
    image: "localhost:5001/gateway:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      ConnectionStrings__cache: "redis"
      services__weather-api__0: "http://weather-api:8080"
      services__weather-api__1: "https://weather-api:8443"
    ports:
    - target: 8080
      published: 10002
    - target: 8443
      published: 10003
    restart: unless-stopped
  web:
    container_name: "web"
    image: "localhost:5001/web:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      services__gateway__0: "http://gateway:8080"
      services__gateway__1: "https://gateway:8443"
    ports:
    - target: 8080
      published: 10004
    - target: 8443
      published: 10005
    restart: unless-stopped
