---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
      - name: weather-api
        image: localhost:5001/weather-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: weather-api-env
        - secretRef:
            name: weather-api-secrets
      terminationGracePeriodSeconds: 180